const Dafalgan = [
  { name: "Dafalgan", expiresIn: 9, benefit: 28 },
  { name: "Dafalgan", expiresIn: 8, benefit: 26 },
  { name: "Dafalgan", expiresIn: 7, benefit: 24 },
  { name: "Dafalgan", expiresIn: 6, benefit: 22 },
  { name: "Dafalgan", expiresIn: 5, benefit: 20 },
  { name: "Dafalgan", expiresIn: 4, benefit: 18 },
  { name: "Dafalgan", expiresIn: 3, benefit: 16 },
  { name: "Dafalgan", expiresIn: 2, benefit: 14 },
  { name: "Dafalgan", expiresIn: 1, benefit: 12 },
  { name: "Dafalgan", expiresIn: 0, benefit: 10 },
  { name: "Dafalgan", expiresIn: -1, benefit: 6 },
  { name: "Dafalgan", expiresIn: -2, benefit: 2 },
  { name: "Dafalgan", expiresIn: -3, benefit: 0 },
  { name: "Dafalgan", expiresIn: -4, benefit: 0 },
  { name: "Dafalgan", expiresIn: -5, benefit: 0 },
  { name: "Dafalgan", expiresIn: -6, benefit: 0 },
  { name: "Dafalgan", expiresIn: -7, benefit: 0 },
  { name: "Dafalgan", expiresIn: -8, benefit: 0 },
  { name: "Dafalgan", expiresIn: -9, benefit: 0 },
  { name: "Dafalgan", expiresIn: -10, benefit: 0 },
  { name: "Dafalgan", expiresIn: -11, benefit: 0 },
  { name: "Dafalgan", expiresIn: -12, benefit: 0 },
  { name: "Dafalgan", expiresIn: -13, benefit: 0 },
  { name: "Dafalgan", expiresIn: -14, benefit: 0 },
  { name: "Dafalgan", expiresIn: -15, benefit: 0 },
  { name: "Dafalgan", expiresIn: -16, benefit: 0 },
  { name: "Dafalgan", expiresIn: -17, benefit: 0 },
  { name: "Dafalgan", expiresIn: -18, benefit: 0 },
  { name: "Dafalgan", expiresIn: -19, benefit: 0 },
  { name: "Dafalgan", expiresIn: -20, benefit: 0 }
];

export default Dafalgan;
