const fervex = [
  { name: "Fervex", expiresIn: 4, benefit: 43 },
  { name: "Fervex", expiresIn: 3, benefit: 46 },
  { name: "Fervex", expiresIn: 2, benefit: 49 },
  { name: "Fervex", expiresIn: 1, benefit: 50 },
  { name: "Fervex", expiresIn: 0, benefit: 50 },
  { name: "Fervex", expiresIn: -1, benefit: 0 },
  { name: "Fervex", expiresIn: -2, benefit: 0 },
  { name: "Fervex", expiresIn: -3, benefit: 0 },
  { name: "Fervex", expiresIn: -4, benefit: 0 },
  { name: "Fervex", expiresIn: -5, benefit: 0 },
  { name: "Fervex", expiresIn: -6, benefit: 0 },
  { name: "Fervex", expiresIn: -7, benefit: 0 },
  { name: "Fervex", expiresIn: -8, benefit: 0 },
  { name: "Fervex", expiresIn: -9, benefit: 0 },
  { name: "Fervex", expiresIn: -10, benefit: 0 },
  { name: "Fervex", expiresIn: -11, benefit: 0 },
  { name: "Fervex", expiresIn: -12, benefit: 0 },
  { name: "Fervex", expiresIn: -13, benefit: 0 },
  { name: "Fervex", expiresIn: -14, benefit: 0 },
  { name: "Fervex", expiresIn: -15, benefit: 0 },
  { name: "Fervex", expiresIn: -16, benefit: 0 },
  { name: "Fervex", expiresIn: -17, benefit: 0 },
  { name: "Fervex", expiresIn: -18, benefit: 0 },
  { name: "Fervex", expiresIn: -19, benefit: 0 },
  { name: "Fervex", expiresIn: -20, benefit: 0 },
  { name: "Fervex", expiresIn: -21, benefit: 0 },
  { name: "Fervex", expiresIn: -22, benefit: 0 },
  { name: "Fervex", expiresIn: -23, benefit: 0 },
  { name: "Fervex", expiresIn: -24, benefit: 0 },
  { name: "Fervex", expiresIn: -25, benefit: 0 }
];

export default fervex;
