const HerbalTea = [
  { name: "Herbal Tea", expiresIn: 9, benefit: 6 },
  { name: "Herbal Tea", expiresIn: 8, benefit: 7 },
  { name: "Herbal Tea", expiresIn: 7, benefit: 8 },
  { name: "Herbal Tea", expiresIn: 6, benefit: 9 },
  { name: "Herbal Tea", expiresIn: 5, benefit: 10 },
  { name: "Herbal Tea", expiresIn: 4, benefit: 11 },
  { name: "Herbal Tea", expiresIn: 3, benefit: 12 },
  { name: "Herbal Tea", expiresIn: 2, benefit: 13 },
  { name: "Herbal Tea", expiresIn: 1, benefit: 14 },
  { name: "Herbal Tea", expiresIn: 0, benefit: 15 },
  { name: "Herbal Tea", expiresIn: -1, benefit: 17 },
  { name: "Herbal Tea", expiresIn: -2, benefit: 19 },
  { name: "Herbal Tea", expiresIn: -3, benefit: 21 },
  { name: "Herbal Tea", expiresIn: -4, benefit: 23 },
  { name: "Herbal Tea", expiresIn: -5, benefit: 25 },
  { name: "Herbal Tea", expiresIn: -6, benefit: 27 },
  { name: "Herbal Tea", expiresIn: -7, benefit: 29 },
  { name: "Herbal Tea", expiresIn: -8, benefit: 31 },
  { name: "Herbal Tea", expiresIn: -9, benefit: 33 },
  { name: "Herbal Tea", expiresIn: -10, benefit: 35 },
  { name: "Herbal Tea", expiresIn: -11, benefit: 37 },
  { name: "Herbal Tea", expiresIn: -12, benefit: 39 },
  { name: "Herbal Tea", expiresIn: -13, benefit: 41 },
  { name: "Herbal Tea", expiresIn: -14, benefit: 43 },
  { name: "Herbal Tea", expiresIn: -15, benefit: 45 },
  { name: "Herbal Tea", expiresIn: -16, benefit: 47 },
  { name: "Herbal Tea", expiresIn: -17, benefit: 49 },
  { name: "Herbal Tea", expiresIn: -18, benefit: 50 },
  { name: "Herbal Tea", expiresIn: -19, benefit: 50 },
  { name: "Herbal Tea", expiresIn: -20, benefit: 50 }
];

export default HerbalTea;
