const MagicPill = [
  { name: "Magic Pill", expiresIn: 15, benefit: 40 },
  { name: "Magic Pill", expiresIn: 15, benefit: 40 },
  { name: "Magic Pill", expiresIn: 15, benefit: 40 },
  { name: "Magic Pill", expiresIn: 15, benefit: 40 },
  { name: "Magic Pill", expiresIn: 15, benefit: 40 },
  { name: "Magic Pill", expiresIn: 15, benefit: 40 },
  { name: "Magic Pill", expiresIn: 15, benefit: 40 },
  { name: "Magic Pill", expiresIn: 15, benefit: 40 },
  { name: "Magic Pill", expiresIn: 15, benefit: 40 },
  { name: "Magic Pill", expiresIn: 15, benefit: 40 },
  { name: "Magic Pill", expiresIn: 15, benefit: 40 },
  { name: "Magic Pill", expiresIn: 15, benefit: 40 },
  { name: "Magic Pill", expiresIn: 15, benefit: 40 },
  { name: "Magic Pill", expiresIn: 15, benefit: 40 },
  { name: "Magic Pill", expiresIn: 15, benefit: 40 },
  { name: "Magic Pill", expiresIn: 15, benefit: 40 },
  { name: "Magic Pill", expiresIn: 15, benefit: 40 },
  { name: "Magic Pill", expiresIn: 15, benefit: 40 },
  { name: "Magic Pill", expiresIn: 15, benefit: 40 },
  { name: "Magic Pill", expiresIn: 15, benefit: 40 },
  { name: "Magic Pill", expiresIn: 15, benefit: 40 },
  { name: "Magic Pill", expiresIn: 15, benefit: 40 },
  { name: "Magic Pill", expiresIn: 15, benefit: 40 },
  { name: "Magic Pill", expiresIn: 15, benefit: 40 },
  { name: "Magic Pill", expiresIn: 15, benefit: 40 },
  { name: "Magic Pill", expiresIn: 15, benefit: 40 },
  { name: "Magic Pill", expiresIn: 15, benefit: 40 },
  { name: "Magic Pill", expiresIn: 15, benefit: 40 },
  { name: "Magic Pill", expiresIn: 15, benefit: 40 },
  { name: "Magic Pill", expiresIn: 15, benefit: 40 }
];

export default MagicPill;
