version: 2
updates:
  - package-ecosystem: "npm"
    directory: '/'
    schedule:
      interval: "daily"
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "all"
      - match:
          dependency_type: "production"
          update_type: "semver:patch"
