root: true
env:
  jest: true
  jest/globals: true
  es6: true
  node: true
parser: "@typescript-eslint/parser"
parserOptions:
  project: "./tsconfig.json"
  ecmaVersion: 2018
  sourceType: module
  noWatch: true

plugins:
  - "@typescript-eslint"
  - import
  - jest
  - prettier
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:prettier/recommended
  - plugin:import/typescript
  - plugin:jest/recommended
settings:
  import/ignore:
    - 'node_modules'
  import/parser:
    '@typescript-eslint/parser':
      - '.ts'
  import/resolver:
    node: {}
    typescript: {}
